# Generated by Django 4.2 on 2023-05-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_sanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sy_id', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(choices=[('first_semester', '1st Semester'), ('second_semester', '2nd Semester')], max_length=30, null=True)),
                ('schoolyear', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sanction',
            options={},
        ),
        migrations.RenameField(
            model_name='sanction',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sanction',
            name='points',
        ),
        migrations.AddField(
            model_name='sanction',
            name='demerit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.event'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='merit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='sanction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear'),
        ),
        migrations.AddField(
            model_name='sanction',
            name='schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='schoolyear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.schoolyear'),
        ),
    ]
