# Generated by Django 4.2 on 2023-05-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_schoolyear_alter_sanction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], max_length=30, null=True),
        ),
    ]
