# Generated by Django 4.2 on 2023-05-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_clearance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clearance',
            new_name='StudentClearance',
        ),
    ]
