# Generated by Django 4.2.1 on 2023-05-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0016_remove_student_email_remove_student_middle_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="id",),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.course",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="year_level",
            field=models.CharField(
                choices=[("I", "I"), ("II", "II"), ("III", "III"), ("IV", "IV")],
                max_length=10,
            ),
        ),
    ]
